# Arquivo de Configuração do Jekyll para o site Pitchutcha

title: Pitchutcha
description: Uma enciclopédia de documentação sobre Ciência da Computação.
baseurl: "/pitchutcha.github.io"

# Configuração do Processador de Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Ignorar os ficheiros do Tailwind na construção do Jekyll
exclude:
  - package.json
  - package-lock.json
  - tailwind.config.js
  - node_modules
  - css/input.css
  - vendor/
