# Arquivo de Configuração do Jekyll para o site Pitchutcha
title: Pitchutcha
description: Uma enciclopédia de documentação sobre Ciência da Computação.

# Nova linha para criar URLs amigáveis e sem acentos
permalink: /:categories/:year/:month/:day/:title:output_ext

# Configuração do Processador de Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
