url: "https://sistemavinculado.github.io"
baseurl: "/pitchutcha.github.io"

# Arquivo de Configuração do Jekyll para o site Pitchutcha

title: Pitchutcha
description: Uma enciclopédia de documentação sobre Ciência da Computação.

# Configuração do Processador de Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Configuração da Coleção de Artigos
collections:
  articles:
    output: true
    permalink: /:collection/:name

# Ativa os plugins listados no Gemfile
plugins:
  - jekyll-minifier

# Configurações do plugin de minificação
jekyll_minifier:
  uglifier_args:
    harmony: true
