# Arquivo de Configuração do Jekyll para o site Pitchutcha

title: Pitchutcha
description: Uma enciclopédia de documentação sobre Ciência da Computação.

# Configuração do Processador de Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# ADICIONE ESTA NOVA SEÇÃO
collections:
  articles:
    output: true
    permalink: /:collection/:name
