# Arquivo de Configuração do Jekyll para o site Pitchutcha

title: Pitchutcha
description: Uma enciclopédia de documentação sobre Ciência da Computação.

# Configuração do Processador de Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Adicione esta seção no final para ignorar os arquivos do Tailwind
exclude:
  - package.json
  - package-lock.json
  - tailwind.config.js
  - node_modules
  - css/input.css
  - vendor/ # <-- ADICIONE ESTA LINHA
