# Arquivo de Configuração do Jekyll para o site Pitchutcha

title: Pitchutcha
description: Uma enciclopédia de documentação sobre Ciência da Computação.

# Configuração do Processador de Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Configuração da Coleção de Artigos
# Isso substitui a necessidade da pasta _posts e do formato de data nos nomes dos arquivos.
collections:
  articles:
    output: true
    permalink: /:collection/:name

# --- RECOMENDAÇÃO DE PERFORMANCE (Requer instalação do plugin) ---
# plugins:
#   - jekyll-minifier

# jekyll_minifier:
#   uglifier_args:
#     harmony: true
