source "https://rubygems.org"

# O gem 'github-pages' gerencia o Jekyll e todas as dependências
# para garantir compatibilidade com o ambiente do GitHub Pages.
gem "github-pages", group: :jekyll_plugins
