source "https://rubygems.org"

# Especifica a versão do Jekyll e seus plugins diretamente
gem "jekyll", "~> 4.3"
gem "jekyll-minifier", "~> 0.2.2"

# Adicionado para compatibilidade com o servidor local do Jekyll 4+
gem "webrick", "~> 1.8"
