name: Construir CSS com Tailwind

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**.html'
      - 'docs/_layouts/**.html'
      - 'docs/_posts/**.md'
      - 'docs/css/input.css'
      - 'docs/tailwind.config.js'
  workflow_dispatch:

jobs:
  build-css:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'docs/package-lock.json'

      - name: Instalar dependências
        run: npm install
        working-directory: ./docs

      - name: Construir o arquivo CSS
        run: npm run build
        working-directory: ./docs

      - name: Fazer commit do novo style.css
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Atualiza o arquivo style.css construído"
          file_pattern: "docs/css/style.css"
