{
  "name": "pitchutcha-docs",
  "version": "1.0.0",
  "description": "Estilos para o site de documentação Pitchutcha.",
  "main": "index.js",
  "scripts": {
    "build": "tailwindcss -i ./css/input.css -o ./css/style.css --minify"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tailwindcss": "^3.4.1",
    "@tailwindcss/forms": "^0.5.7",
    "@tailwindcss/container-queries": "^0.1.0"
  }
}
