name: Download Pyodide Locally

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-pyodide:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Create Pyodide vendor directory
        run: mkdir -p docs/js/vendor/pyodide

      - name: Download and Unzip Pyodide Distribution Files
        run: |
          PYODIDE_VERSION="v0.25.1"
          # 1. Baixa o arquivo .tar.bz2 que contém APENAS a pasta 'dist'
          curl -L https://github.com/pyodide/pyodide/releases/download/${PYODIDE_VERSION}/pyodide-dist-${PYODIDE_VERSION}.tar.bz2 -o pyodide-dist.tar.bz2
          
          # 2. Extrai o conteúdo diretamente para a nossa pasta de destino
          #    Como este arquivo contém apenas a pasta 'dist', o --strip-components=1 remove a pasta 'dist'
          #    e joga todo o seu conteúdo dentro de 'docs/js/vendor/pyodide/'
          tar -xvf pyodide-dist.tar.bz2 --directory docs/js/vendor/pyodide --strip-components=1

      - name: Commit Pyodide files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add Pyodide distribution files locally"
          file_pattern: "docs/js/vendor/pyodide"
