name: Download Pyodide Locally

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-pyodide:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Create Pyodide vendor directory
        run: mkdir -p docs/js/vendor/pyodide

      - name: Download and Unzip Pyodide
        run: |
          set -ex # Modo de depuração para falhar em qualquer erro
          
          PYODIDE_VERSION="v0.25.1"
          
          # 1. Baixa o arquivo .tar.bz2 COMPLETO (o link correto)
          curl -L https://github.com/pyodide/pyodide/releases/download/${PYODIDE_VERSION}/pyodide-${PYODIDE_VERSION}.tar.bz2 -o pyodide.tar.bz2
          
          # 2. Cria uma pasta temporária para extração controlada
          mkdir pyodide-temp
          
          # 3. Extrai o conteúdo para dentro da pasta temporária, removendo o diretório-pai do arquivo
          tar -xvf pyodide.tar.bz2 -C pyodide-temp --strip-components=1
          
          # 4. Copia APENAS a pasta 'dist' de dentro da extração para o nosso destino final
          cp -r pyodide-temp/dist/* docs/js/vendor/pyodide/

      - name: Commit Pyodide files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add Pyodide distribution files locally"
          file_pattern: "docs/js/vendor/pyodide"
