name: Baixar e Atualizar Fontes Locais

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-fonts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Baixar Google Fonts (Inter, Noto Sans, JetBrains Mono)
        uses: fonts-actions/google-fonts@v2
        with:
          fonts: |
            Inter:wght@400;500;600;700
            Noto Sans:wght@400;500;600;700
            JetBrains Mono:wght@400;500
          output_dir: docs/fonts

      - name: Commit and push font files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Update local fonts and add JetBrains Mono"
          file_pattern: "docs/fonts"
