# Nome do Workflow: Baixar e Atualizar Fontes Locais
name: Baixar e Atualizar Fontes Locais

on:
  workflow_dispatch:

jobs:
  download-fonts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Baixar Google Fonts (usando Muetze42)
        # Usando a action que você sugeriu
        uses: Muetze42/google-fonts-downloader@v1.1.1 # Usando uma versão específica
        with:
          # O nome do parâmetro aqui é 'font_families'
          font_families: 'Inter:400,500,600,700|Noto Sans:400,500,600,700|JetBrains Mono:400,500'
          # O diretório de saída
          output_dir: "docs/fonts"
          # Formatos desejados
          formats: 'woff2'
          
      - name: Commit and push font files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Update local fonts and add JetBrains Mono"
          file_pattern: "docs/fonts/**"
