name: Download Pyodide Locally

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-pyodide:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Create Pyodide vendor directory
        run: mkdir -p docs/js/vendor/pyodide

      # --- ETAPA DE DOWNLOAD REFEITA PARA SER MAIS ROBUSTA ---
      - name: Download and Unzip Pyodide
        run: |
          PYODIDE_VERSION="v0.25.1"
          # 1. Baixa o arquivo como antes
          curl -L https://github.com/pyodide/pyodide/releases/download/${PYODIDE_VERSION}/pyodide-${PYODIDE_VERSION}.tar.bz2 -o pyodide.tar.bz2
          
          # 2. Cria uma pasta temporária com um nome que NÓS controlamos
          mkdir pyodide-temp
          
          # 3. Extrai o conteúdo do arquivo para dentro da nossa pasta temporária
          #    --strip-components=1 remove o diretório-pai de dentro do .tar.bz2
          tar -xvf pyodide.tar.bz2 -C pyodide-temp --strip-components=1
          
          # 4. Copia os arquivos de um caminho agora 100% previsível
          cp -r pyodide-temp/dist/* docs/js/vendor/pyodide/

      - name: Commit Pyodide files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add Pyodide files locally to vendor directory"
          file_pattern: "docs/js/vendor/pyodide"
