# Nome do Workflow: Baixar e Atualizar Fontes Locais
name: Baixar e Atualizar Fontes Locais

# Define o gatilho para execução manual através da interface do GitHub
on:
  workflow_dispatch:

# Define os jobs que serão executados
jobs:
  # Nome do job
  download-fonts:
    # O tipo de máquina virtual para rodar o job
    runs-on: ubuntu-latest
    
    # Define as permissões necessárias para o token do GitHub Actions
    permissions:
      # Permissão de escrita no repositório para fazer o commit das fontes
      contents: write
      
    # Define a sequência de passos a serem executados no job
    steps:
      # 1. Faz o checkout do código do repositório para a máquina virtual
      - name: Check out repo
        uses: actions/checkout@v4

      # 2. Baixa as fontes do Google Fonts usando a action correta
      - name: Baixar Google Fonts (Inter, Noto Sans, JetBrains Mono)
        # CORREÇÃO: Usando a action 'rickstaa/google-fonts-downloader' que é funcional
        uses: rickstaa/google-fonts-downloader@v1
        with:
          # Lista de fontes e pesos a serem baixados (sintaxe ajustada para a nova action)
          fonts: |
            Inter:400,500,600,700
            Noto Sans:400,500,600,700
            JetBrains Mono:400,500
          # Diretório de destino para os arquivos das fontes
          output_dir: "docs/fonts"
          # Opcional: Especifica que queremos apenas o formato woff2 para otimização
          formats: "woff2"
          
      # 3. Faz o commit e push automático dos arquivos de fontes baixados
      - name: Commit and push font files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensagem do commit
          commit_message: "feat: Update local fonts and add JetBrains Mono"
          # Padrão de arquivos para incluir no commit
          file_pattern: "docs/fonts/**" # Adicionado /** para garantir a captura de todos os arquivos no diretório
