name: Download Pyodide Locally

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-pyodide:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Create Pyodide vendor directory
        run: mkdir -p docs/js/vendor/pyodide

      - name: Download and Extract Pyodide Release Asset
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "pyodide/pyodide"
          tag: "0.28.2"
          fileName: "pyodide-build-0.28.2.tar.bz2" # Nome correto para a v0.28.2
          extract: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Extracted Files and Move to Vendor
        run: |
          set -ex
          ls -R
          # O caminho da pasta extraída corresponde à nova versão
          cp -r pyodide-build-0.28.2/* docs/js/vendor/pyodide/

      - name: Commit Pyodide files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add Pyodide v0.28.2 files locally"
          file_pattern: "docs/js/vendor/pyodide"
