name: Baixar e Atualizar Fontes Locais

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-fonts:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para fazer commit no repositório
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Baixar Google Fonts (Inter e Noto Sans)
        uses: roryg/google-font-download@v1
        with:
          fonts: |
            - family: Inter
              variants: [400, 500, 700, 900]
              subsets: [latin]
            - family: Noto Sans
              variants: [400, 500, 700, 900]
              subsets: [latin]
          outputDir: docs/fonts
          
      - name: Commit and push font files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add local fonts (Inter, Noto Sans)"
          file_pattern: "docs/fonts/*.*"

        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add local fonts (Inter, Noto Sans)"
          file_pattern: "docs/fonts/*.*"
