name: Download Pyodide Locally

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-pyodide:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Create Pyodide vendor directory
        run: mkdir -p docs/js/vendor/pyodide

      - name: Download and Unzip Pyodide
        run: |
          PYODIDE_VERSION="v0.25.1"
          curl -L https://github.com/pyodide/pyodide/releases/download/${PYODIDE_VERSION}/pyodide-${PYODIDE_VERSION}.tar.bz2 -o pyodide.tar.bz2
          tar -xvf pyodide.tar.bz2
          # Copia apenas os arquivos de distribuição para a nossa pasta vendor
          cp -r pyodide/dist/* docs/js/vendor/pyodide/

      - name: Commit Pyodide files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add Pyodide files locally to vendor directory"
          file_pattern: "docs/js/vendor/pyodide"
          # Adiciona LFS para arquivos grandes se necessário (descomente se o push falhar)
          # commit_options: '--all --force'
          # push_options: '--force'
