name: Download Pyodide Locally

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-pyodide:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Create Pyodide vendor directory
        run: mkdir -p docs/js/vendor/pyodide

      - name: Download and Extract Pyodide Release Asset
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "pyodide/pyodide"
          tag: "0.25.1"
          # CORREÇÃO FINAL: Usando o nome de arquivo exato do release
          fileName: "pyodide-src-0.25.1.tar.bz2"
          extract: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Extracted Files and Move to Vendor
        run: |
          set -ex
          echo "--- Verificando a estrutura de pastas extraída ---"
          ls -R
          
          echo "--- Movendo os arquivos da pasta 'dist' para o destino ---"
          # A pasta extraída terá o mesmo nome do arquivo, com '-src-'
          cp -r pyodide-src-0.25.1/dist/* docs/js/vendor/pyodide/

      - name: Commit Pyodide files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add Pyodide distribution files locally"
          file_pattern: "docs/js/vendor/pyodide"
