name: Download Pyodide Locally

on:
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  download-pyodide:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Create Pyodide vendor directory
        run: mkdir -p docs/js/vendor/pyodide

      - name: Download Release Asset using GitHub CLI
        run: |
          gh release download 0.28.2 \
            --repo pyodide/pyodide \
            --pattern "pyodide-build-0.28.2.tar.bz2" \
            --output pyodide.tar.bz2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract and Move Files
        run: |
          set -ex
          ls -l # Mostra o arquivo baixado
          mkdir pyodide-extract
          tar -xvf pyodide.tar.bz2 -C pyodide-extract --strip-components=1
          cp -r pyodide-extract/* docs/js/vendor/pyodide/

      - name: Commit Pyodide files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add Pyodide v0.28.2 files locally"
          file_pattern: "docs/js/vendor/pyodide"
