name: Gerar Subconjunto de Fontes
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Instalar FontTools
        run: pip install fonttools brotli zopfli
      - name: Gerar subconjunto de fontes
        run: |
          TEXT_CONTENT=$(grep -rhEo '[a-zA-Z0-9çãáéíóúâêôàüÇÃÁÉÍÓÚÂÊÔÀÜ:;.,!?"@#$%&*\(\)_+=\[\]{}<>/\-–—|`~^ ]+' docs/ | tr -d '\\n' | sort -u | tr -d '[:space:]')
          if [ -z "$TEXT_CONTENT" ]; then
            echo "Nenhum texto encontrado para gerar o subconjunto. Saindo."
            exit 0
          fi
          echo "Caracteres para o subconjunto: $TEXT_CONTENT"
          for font in docs/fonts/*.woff2; do
            echo "Processando $font"
            pyftsubset "$font" --output-file="$font.subset" --text="$TEXT_CONTENT" --flavor=woff2 --with-zopfli
            mv "$font.subset" "$font"
          done
      - name: Fazer commit das fontes otimizadas
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Atualiza fontes com subconjuntos otimizados'
          file_pattern: 'docs/fonts/**.woff2'

