name: Compress Images

on:
  pull_request:
    # Executa a Action quando arquivos JPG, JPEG, PNG, WebP ou AVIF são adicionados ou alterados.
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '**.avif'
  workflow_dispatch:

jobs:
  compress-images: # Nome do job alterado para ser mais descritivo
    # Executa apenas em Pull Requests do mesmo repositório, não de forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Compress Images with Calibre
    runs-on: ubuntu-latest
    
    # Boas práticas: Use permissões mínimas necessárias.
    permissions:
      contents: write # Necessário para fazer o commit das imagens otimizadas
      pull-requests: write # Necessário para comentar no PR

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        # Use uma versão principal estável (@v1) em vez de @main para evitar quebras inesperadas.
        uses: calibreapp/image-actions@v1 
        with:
          # O bloco 'with' deve estar indentado sob o passo 'uses'.
          jpegQuality: '85'
          jpegProgressive: false
          pngQuality: '80'
          webpQuality: '85'
          avifQuality: '75'
          # Adicione o token do GitHub para que a action possa fazer commits
          githubToken: ${{ secrets.GITHUB_TOKEN }}
