# Nome do Workflow: Otimizar Imagens
name: Optimize Images

on:
  pull_request:
    # CORREÇÃO: Monitora apenas as pastas de assets relevantes para maior eficiência.
    paths:
      - 'docs/assets/images/**.{jpg,jpeg,png,webp,avif}'
      - 'docs/assets/logos/**.{jpg,jpeg,png,webp,avif}'
  # Permite o acionamento manual
  workflow_dispatch:

jobs:
  compress-images:
    # CORREÇÃO: Executa o job em Pull Requests do mesmo repositório OU em acionamentos manuais.
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
    name: Compress Images with Calibre
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@v1 
        with:
          # Token do GitHub para permitir que a action faça commits e comente no PR.
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
          # Suas configurações de qualidade de imagem:
          jpegQuality: '85'
          jpegProgressive: false
          pngQuality: '80'
          webpQuality: '85'
          avifQuality: '75'
