# Nome do Workflow
name: Auditoria Lighthouse

# Gatilhos: Roda toda segunda-feira às 8h da manhã ou manualmente
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  lighthouse-audit:
    name: Rodar Auditoria Lighthouse
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para fazer commit no repositório

    steps:
      # 1. Faz o checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Cria arquivos de configuração para Celular e Computador
      - name: Criar Configurações do Lighthouse
        run: |
          # Configuração para Celular (padrão)
          echo '{
            "ci": {
              "assert": {
                "assertions": {
                  "categories:performance": ["warn", { "minScore": 0.6 }],
                  "categories:accessibility": ["warn", { "minScore": 0.8 }],
                  "categories:best-practices": ["warn", { "minScore": 0.8 }],
                  "categories:seo": ["warn", { "minScore": 0.7 }]
                }
              }
            }
          }' > ./.lighthouserc-mobile.json
          # Configuração para Computador (com "preset: desktop")
          echo '{
            "ci": {
              "collect": {
                "settings": {
                  "preset": "desktop"
                }
              },
              "assert": {
                "assertions": {
                  "categories:performance": ["warn", { "minScore": 0.8 }],
                  "categories:accessibility": ["warn", { "minScore": 0.8 }],
                  "categories:best-practices": ["warn", { "minScore": 0.8 }],
                  "categories:seo": ["warn", { "minScore": 0.8 }]
                }
              }
            }
          }' > ./.lighthouserc-desktop.json

      # 3. Roda a auditoria para CELULAR
      - name: Rodar Lighthouse CI (Celular)
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://sistemavinculado.github.io/pitchutcha.github.io/
          uploadArtifacts: true
          artifactName: lighthouse-report-mobile
          temporaryPublicStorage: true
          configPath: './.lighthouserc-mobile.json'
      
      - name: Renomear Relatório de Celular
        run: |
          REPORT_PATH=$(ls -t .lighthouseci/lhr-*.json | head -n 1)
          mv $REPORT_PATH ./.lighthouseci/lhr-mobile.json

      # 4. Roda a auditoria para COMPUTADOR
      - name: Rodar Lighthouse CI (Computador)
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://sistemavinculado.github.io/pitchutcha.github.io/
          uploadArtifacts: true
          artifactName: lighthouse-report-desktop
          temporaryPublicStorage: true
          configPath: './.lighthouserc-desktop.json'
      
      # 5. Renomeia o Relatório de Computador (Lógica Corrigida)
      - name: Renomear Relatório de Computador
        run: |
          # Encontra o arquivo JSON que AINDA NÃO foi renomeado para lhr-mobile.json
          REPORT_PATH=$(find .lighthouseci -name "lhr-*.json" ! -name "lhr-mobile.json")
          mv $REPORT_PATH ./.lighthouseci/lhr-desktop.json

      # 6. Processa e combina os dois relatórios
      - name: Processar e Combinar Relatórios
        run: |
          JQ_EXTRACT_FUNCTION='
          def extract: {
            scores: {
              performance: (.categories.performance.score * 100 | round),
              accessibility: (.categories.accessibility.score * 100 | round),
              bestPractices: (.categories."best-practices".score * 100 | round),
              seo: (.categories.seo.score * 100 | round)
            },
            metrics: {
              fcp: .audits["first-contentful-paint"].displayValue,
              lcp: .audits["largest-contentful-paint"].displayValue,
              tbt: .audits["total-blocking-time"].displayValue,
              cls: .audits["cumulative-layout-shift"].displayValue,
              si: .audits["speed-index"].displayValue
            },
            opportunities: ([.audits.opportunities.details.items[]? | select(.overallSavingsMs > 0) | {title: .title, savings: (.overallSavingsMs / 1000 | tostring + " s")}] | .[:3])
          };'
          
          jq -n "$JQ_EXTRACT_FUNCTION"'
          {
            mobile: (input | extract),
            desktop: (input | extract)
          }' ./.lighthouseci/lhr-mobile.json ./.lighthouseci/lhr-desktop.json > ./docs/pagespeed-data.json

      # 7. Faz o commit do novo arquivo de dados
      - name: Fazer commit do arquivo pagespeed-data.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Atualiza os dados de auditoria do Lighthouse (Celular e Computador)"
          file_pattern: "docs/pagespeed-data.json"
