name: Verificador de Links Quebrados

on:
  workflow_dispatch: # Permite iniciar manualmente
  schedule:
    - cron: '0 8 * * 1' # Executa toda segunda-feira às 8h da manhã

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Verificador de Links Lychee no Site Ao Vivo
        uses: lychee-action/lychee-action@v1.9.0
        with:
          # Substitua pela URL principal do seu site
          args: --verbose --no-progress https://sistemavinculado.github.io/pitchutcha.github.io/
        env:
          # Usa um token do GitHub para evitar limites de taxa ao verificar links do GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
