name: Diagnóstico Completo do Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-diagnostics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências (puppeteer)
        run: npm install puppeteer

      - name: Executar script de diagnóstico
        run: node scripts/run-diagnostics.mjs

      - name: Fazer commit do relatório de diagnóstico
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Atualiza o relatório de diagnóstico do site"
          file_pattern: "docs/diagnostics.json"
